apiVersion: v1
kind: ConfigMap
metadata:
  name: cashflow-config
  namespace: cashflow
data:
  KEYCLOAK_AUTHORITY: "https://keycloak.cashflow.svc.cluster.local/realms/cashflow"
  KEYCLOAK_AUDIENCE: "cashflow-api"
  TRANSACTION_API_URL: "http://transaction-api:8080/"
  BALANCE_QUERY_API_URL: "http://balance-query-api:8080/"
  REDIS_CONNECTION: "redis:6379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  OTEL_ENDPOINT: "http://otel-collector:4317"
  GATEWAY_RATE_LIMIT_GLOBAL_PERMIT_LIMIT: "100"
  GATEWAY_RATE_LIMIT_GLOBAL_WINDOW_SECONDS: "1"
  GATEWAY_RATE_LIMIT_GLOBAL_QUEUE_LIMIT: "50"
  GATEWAY_RATE_LIMIT_TRANSACTION_WRITE_PERMIT_LIMIT: "40"
  GATEWAY_RATE_LIMIT_TRANSACTION_WRITE_WINDOW_SECONDS: "1"
  GATEWAY_RATE_LIMIT_TRANSACTION_WRITE_QUEUE_LIMIT: "20"
  GATEWAY_RATE_LIMIT_TRANSACTION_READ_PERMIT_LIMIT: "120"
  GATEWAY_RATE_LIMIT_TRANSACTION_READ_WINDOW_SECONDS: "1"
  GATEWAY_RATE_LIMIT_TRANSACTION_READ_QUEUE_LIMIT: "40"
  GATEWAY_RATE_LIMIT_BALANCE_READ_PERMIT_LIMIT: "150"
  GATEWAY_RATE_LIMIT_BALANCE_READ_WINDOW_SECONDS: "1"
  GATEWAY_RATE_LIMIT_BALANCE_READ_QUEUE_LIMIT: "60"
