apiVersion: v1
kind: Secret
metadata:
  name: cashflow-secrets
  namespace: cashflow
type: Opaque
stringData:
  CONNECTIONSTRINGS__POSTGRES: "Host=postgres;Port=5432;Database=cashflow;Username=postgres;Password=replace-me"
  RABBITMQ__USERNAME: "guest"
  RABBITMQ__PASSWORD: "replace-me"
  TLS_CERT_PASSWORD: "replace-me"
